### ISSUE TITLE
Dry-run mode

### ISSUE THREAD

**Issue by lolo101** [fabiospampinato/bump#34]
Hi !

It would be nice to have a dry-run mode to test various options before actually running the command and throwing stuff to the npm registry

**Comment by fabiospampinato** [comment]
Would this be any more useful than the already present `--no-scripts` flag?

**Comment by lolo101** [comment]
IDK :slightly_smiling_face: 

I cannot find any documentation about this flag in the readme or the CLI help
What does it do?

**Comment by fabiospampinato** [comment]
I should update the screenshot in the readme, it basically just turns off all pre and post scripts.

**Comment by fabiospampinato** [comment]
what do you get with a `npx bump --version`?

**Comment by lolo101** [comment]
OMG, I'm so sorry I think I have another executable named "bump".

When I use the fully qualified name of the package I get the following:
```
$ npx @fabiospampinato/bump --version
3.2.2
```

However, I think there is some issue here : 
```
$ npx @fabiospampinato/bump major --no-scripts
TypeError: unmatched.replaceAll is not a function or its return value is not iterable
    at getStringTruncatedWidth (file:///home/loic/.npm/_npx/a9f0ddfae1f1b021/node_modules/fast-string-truncated-width/dist/index.js:42:42)
    at truncate (file:///home/loic/.npm/_npx/a9f0ddfae1f1b021/node_modules/ansi-truncate/dist/index.js:10:44)
    at truncate (file:///home/loic/.npm/_npx/a9f0ddfae1f1b021/node_modules/tiny-truncate/dist/index.js:6:12)
    at writeLine (file:///home/loic/.npm/_npx/a9f0ddfae1f1b021/node_modules/tiny-spinner/dist/utils.js:5:12)
    at Spinner.stop (file:///home/loic/.npm/_npx/a9f0ddfae1f1b021/node_modules/tiny-spinner/dist/index.js:46:13)
    at Spinner.error (file:///home/loic/.npm/_npx/a9f0ddfae1f1b021/node_modules/tiny-spinner/dist/index.js:37:25)
    at command (file:///home/loic/.npm/_npx/a9f0ddfae1f1b021/node_modules/@fabiospampinato/bump/dist/commands/command.js:19:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```
Note: the package.json has been updated as expected

BTW with a dry run, I would expect the package.json to be left unmodified

**Comment by fabiospampinato** [comment]
Oh right this package is namespaced unfortunately.

It looks like there is a bug somewhere 🤔

> BTW with a dry run, I would expect the package.json to be left unmodified

What would you expect a dry run mode to actually do?

**Comment by lolo101** [comment]
I'd expect the dry run to do nothing at all, but print a detailed log of what it _would_ do. Just like if it would be an actual run. So I can tell if I misconfigured something, if the version is not the one I expect, or if the access to the npm repository is misconfigured, and so on

**Comment by lolo101** [comment]
For instance you can check the dry-run mode of release-it

https://github.com/release-it/release-it?tab=readme-ov-file#dry-runs

**Comment by fabiospampinato** [comment]
It makes sense, but assuming the bug you reported is fixed, wouldn't it be more or less the same as doing a `bump --no-scripts`, looking at the changes in git, and then discarding all local changes in git? Like I understand that having a `--dry-run` command could be a bit more convenient, but it would also the program more complicated for maybe not enough benefit 🤔

**Comment by lolo101** [comment]
Yes good point :slightly_smiling_face: 

I'll try this and let you know, thank you for taking the time to take a look at this request anyway :wink:

**Comment by fabiospampinato** [comment]
Possibly a better suggestion, but you can just run `bump version && bump changelog` for example to skip making the commit and tagging it, which make resetting the changes a bit more annoying.

**Comment by fabiospampinato** [comment]
By the way are you using a version older than v15 of Node? The error you are seeing about `String.prototype.replaceAll` not being available seems to indicate that.
